workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-(ce|ee)$/'
    - changes:
        - dockerfiles/*/version-manifests.json
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - when: never

stages:
  - detect
  - trigger
  - build
  - package

variables:
  # Docker
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  # Build settings
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  BUILD_PLATFORMS: "linux/arm64,linux/amd64"
  REGISTRY: "opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public"
  # Go Env
  GO111MODULE: "on"
  GOPROXY: "https://goproxy.cn,direct"
  # Git
  GIT_SUBMODULE_FORCE_HTTPS: true
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_DEPTH: 1
  # OS
  OS_RELEASE: "ubuntu:22.04"
  TAG: ubuntu_22.04

trigger-generate:
  stage: trigger
  trigger:
    include:
      - local: .gitlab/.generate.gitlab-ci.yml
        inputs:
          tag: "$TAG"
    forward:
      pipeline_variables: true
    strategy: depend

