services:
  csghub:
    container_name: csghub
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/omnibus-csghub:2.0
    hostname: 'csghub.example.com'
    environment:
      CSGHUB_OMNIBUS_CONFIG: |
        csghub:
          external_url: "http://csghub.example.com"
    ports:
      - '80:80'
      - '2222:2222'
      - '5000:5000'
      - '8000:8000'
      - '9000:9000'
    volumes:
      - csghub_etc:/etc/csghub
      - csghub_logs:/var/log/csghub
      - csghub_data:/var/opt/csghub
      - csghub_kube:/etc/csghub/.kube
    restart: always
    shm_size: '256m'

volumes:
  csghub_etc:
  csghub_logs:
  csghub_data:
  csghub_kube: