ARG REGISTRY=docker.io
ARG OS_RELEASE=ubuntu:22.04

FROM ${REGISTRY}/${OS_RELEASE} AS builder
WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded
ENV CSGHUB_SRV_HOME=${CSGHUB_EMBEDDED}/sv

## Install postgresql
RUN if grep -q -i -E 'ubuntu|debian' /etc/os-release; then \
        apt update && \
        apt install -y --no-install-recommends \
          gcc flex bison make wget bzip2 clang git \
          libicu-dev \
          build-essential \
          libreadline-dev \
          libssl-dev \
          zlib1g-dev \
          pkg-config \
          ca-certificates && \
        apt clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/*; \
    else \
        if command -v dnf >/dev/null; then \
            dnf install -y \
              gcc flex bison make wget bzip2 clang git \
              libicu-devel \
              readline-devel \
              openssl-devel \
              zlib-devel \
              pkgconfig \
              ca-certificates && \
            dnf clean all; \
        else \
            yum install -y \
              gcc flex bison make wget bzip2 clang git \
              libicu-devel \
              readline-devel \
              openssl-devel \
              zlib-devel \
              pkgconfig \
              ca-certificates && \
            yum clean all; \
        fi; \
        rm -rf /var/cache/yum /tmp/* /var/tmp/* /var/log/*; \
    fi

ARG POSTGRESQL_VERSION=15.17
RUN wget https://ftp.postgresql.org/pub/source/v${POSTGRESQL_VERSION}/postgresql-${POSTGRESQL_VERSION}.tar.gz && \
    mkdir /postgresql && tar --strip-components=1 -zxf postgresql-${POSTGRESQL_VERSION}.tar.gz -C /postgresql && \
    cd /postgresql && ./configure --prefix=${CSGHUB_SRV_HOME}/postgresql \
      --with-openssl \
      --with-icu \
      --with-readline && \
    make world && make install-world

# Compile zhparser
ENV PGHOME=${CSGHUB_SRV_HOME}/postgresql
ENV LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$PGHOME/lib \
    PATH=$PGHOME/bin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin:\$PATH

ARG SCWS_VERSION=1.2.3
RUN wget http://www.xunsearch.com/scws/down/scws-${SCWS_VERSION}.tar.bz2 && \
    mkdir /scws && tar --strip-components=1 -xjf scws-${SCWS_VERSION}.tar.bz2 -C /scws && \
    cd /scws && ./configure --prefix=${CSGHUB_EMBEDDED} && make install

ENV SCWS_HOME=${CSGHUB_EMBEDDED}
RUN git clone https://github.com/amutu/zhparser.git && \
    cd /zhparser && make && make install

FROM ${REGISTRY}/${OS_RELEASE}

WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded
ENV CSGHUB_SRV_HOME=${CSGHUB_EMBEDDED}/sv

COPY --from=builder /opt/. /opt/
