services:
  csghub:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/omnibus-csghub:v1.8.0-ce
    hostname: 'csghub.example.com'
    environment:
      CSGHUB_OMNIBUS_CONFIG: |
        csghub:
          external_url: "http://csghub.example.com"
        runner:
          enable: true
          deploy:
            knative:
              services:
                - type: "NodePort"
                  domain: "app.internal"
                  host: "192.168.18.10"
                  port: 30123
    ports:
      - '80:80'
      - '2222:2222'
      - '5000:5000'
      - '8000:8000'
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./csghub/etc:/etc/csghub
      - ./csghub/logs:/var/log/csghub
      - ./csghub/data:/var/opt/csghub
      - ./csghub/.kube:/etc/csghub/.kube
    restart: always
    shm_size: '256m'
