spec:
  inputs:
    tag:
      description: "Runner tags"
      default: 'ubuntu_22.04'
---
default:
  services:
    - name: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/docker:28.2-dind
      command: [ "--feature=containerd-snapshotter", "--experimental" ]
      alias: docker
  retry: 2

stages:
  - prepare
  - build
  - package
  - upload

variables:
  # Docker
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  # Package
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/omnibus/${CI_COMMIT_TAG}"

build-omnibus-$[[ inputs.tag ]]:
  stage: build
  image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/docker:28.2
  before_script:
    - sed -i 's|http[s]*://dl-cdn.alpinelinux.org|https://mirrors.tuna.tsinghua.edu.cn|g' /etc/apk/repositories
    - apk update && apk add jq bash
    - |
      set -e
      echo "Merging version manifests..."
      tmpfile=$(mktemp)
      jq -n '{components: [inputs.components[]]}' dockerfiles/*/version-manifests.json | \
      jq -s '.[0] as $components | .[1] | .version_manifest.components = (.version_manifest.components + $components.components) | .' - opt/csghub/version-manifests.json > "$tmpfile"

      if ! jq empty "$tmpfile"; then
        echo "Error: Invalid JSON generated"
        rm -f "$tmpfile"
        exit 1
      fi

      mv "$tmpfile" opt/csghub/version-manifests.json
      echo "Version manifest successfully updated"

      echo "Merged version-manifests.json:"
      jq . opt/csghub/version-manifests.json
    - sed -i 's|http[s]*://dl-cdn.alpinelinux.org|https://mirrors.tuna.tsinghua.edu.cn|g' /etc/apk/repositories
    - apk add jq bash
    - docker run --privileged --rm opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/tonistiigi/binfmt --install all
    - echo "$ACR_PASSWORD" | docker login -u $ACR_USERNAME $ACR_REGISTRY --password-stdin
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - |
      cat <<'EOF' | bash -s
      # Collect build parameters for all components
      BUILD_ARGS=$(jq -r '.version_manifest.components[] | "--build-arg \(.name | ascii_upcase | gsub("-"; "_"))_VERSION=\(.version)"' opt/csghub/version-manifests.json | tr '\n' ' ')

      OS_TAG=$(basename $OS_RELEASE | sed 's/:/_/g')
      BUILD_ARGS+=(
        "--build-arg" "OS_RELEASE=${OS_RELEASE}"
        "--build-arg" "OS_TAG=${OS_TAG}"
        "--build-arg" "REGISTRY=${REGISTRY}"
        "--build-arg" "CSGHUB_VERSION=${CI_COMMIT_TAG}"
        "--build-arg" "GITALY_VERSION=${GITALY_VERSION}"
        "--build-arg" "GITLAB_SHELL_VERSION=${GITLAB_SHELL_VERSION}"
      )

      IMAGE="${ACR_REGISTRY}/opencsghq/omnibus-csghub:${CI_COMMIT_TAG}-${OS_TAG}"
      # Initialize the label array
      TAGS=(
        "-t" "${IMAGE}"
      )

      # If it is ubuntu:22.04, add an additional tag
      if [ "$OS_RELEASE" = "ubuntu:22.04" ]; then
        TAGS+=(
          "-t" "${ACR_REGISTRY}/opencsghq/omnibus-csghub:${CI_COMMIT_TAG}"
        )
      fi

      if [[ "$CI_COMMIT_TAG" =~ ce ]]; then
        DOCKERFILE=Dockerfile
      else
        DOCKERFILE=ee.Dockerfile
      fi

      BUILD_PLATFORMS_CNT=$(echo "$BUILD_PLATFORMS" | tr ',' '\n' | wc -l)
      if [[ $BUILD_PLATFORMS_CNT -eq 1 ]]; then
        if docker manifest inspect ${IMAGE} >/dev/null 2>&1; then
          IMAGE_CNT=1
        else
          IMAGE_CNT=0
        fi
      elif [[ $BUILD_PLATFORMS_CNT -eq 2 ]]; then
        IMAGE_CNT=$(docker manifest inspect ${IMAGE} 2>/dev/null| egrep -c 'amd64|arm64')
      fi

      if [[ $IMAGE_CNT -ne $BUILD_PLATFORMS_CNT || $REBUILD_FORCE == "true" ]]; then
        docker buildx build \
          --provenance false \
          --platform ${BUILD_PLATFORMS} \
          ${BUILD_ARGS[@]} \
          ${TAGS[@]} \
          -f ${DOCKERFILE} \
          --push .
      else
        echo "Image ${IMAGE} already exists."
      fi
      EOF
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG

pack-omnibus-$[[ inputs.tag ]]:
  stage: package
  image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/docker:28.2
  before_script:
    - sed -i 's|http[s]*://dl-cdn.alpinelinux.org|https://mirrors.tuna.tsinghua.edu.cn|g' /etc/apk/repositories
    - apk add jq bash
    - docker run --privileged --rm opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/tonistiigi/binfmt --install all
  script:
    - |
      cat <<'EOF' | bash -s
      OS_TAG=$(basename $OS_RELEASE | sed 's/:/_/g')
      BUILD_ARGS+=( 
        "--build-arg" "OS_RELEASE=${OS_RELEASE}" 
        "--build-arg" "OS_TAG=${OS_TAG}" 
        "--build-arg" "REGISTRY=${REGISTRY}" 
        "--build-arg" "CSGHUB_VERSION=${CI_COMMIT_TAG}" 
      )
      
      if [[ "$OS_RELEASE" =~ ubuntu|debian ]]; then
        DOCKERFILE="packages/Dockerfile_debian_based"
      else
        DOCKERFILE="packages/Dockerfile_rhel_based"
      fi
      
      docker buildx build \
        --provenance false \
        --platform ${BUILD_PLATFORMS} \
        ${BUILD_ARGS[@]} \
        -f ${DOCKERFILE} \
        -o packages .
      EOF
  dependencies:
    - build-omnibus-$[[ inputs.tag ]]
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - packages/linux_*
      - packages/*.deb
      - packages/*.rpm

upload-omnibus-$[[ inputs.tag ]]:
  stage: upload
  image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/curlimages/curl:latest
  script:
    - |
      for FILE in $(find packages -name "*.deb" -o -name "*.rpm"); do
        curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${FILE} "${PACKAGE_REGISTRY_URL}/$(basename $FILE)"
      done
  needs:
    - pack-omnibus-$[[ inputs.tag ]]
  rules:
    - if: $CI_COMMIT_TAG
