ARG OS_RELEASE=ubuntu:22.04
FROM ${OS_RELEASE}
WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded

RUN apt update && \
    apt install -y --no-install-recommends \
      wget build-essential && \
    apt clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/* && \
    mkdir -p ${CSGHUB_EMBEDDED}/bin

## Install Runit Service Daemon
ARG RUNIT_VERSION=2.1.2
RUN wget --no-check-certificate https://smarden.org/runit/runit-${RUNIT_VERSION}.tar.gz && \
    tar -zxf runit-${RUNIT_VERSION}.tar.gz && \
    cd /admin/runit-${RUNIT_VERSION} && package/install && \
    cp command/* ${CSGHUB_EMBEDDED}/bin && \
    rm -rf /admin/runit-${RUNIT_VERSION} /runit-${RUNIT_VERSION}.tar.gz

RUN chmod +x -R ${CSGHUB_EMBEDDED}/bin
