ARG OS_RELEASE=ubuntu:22.04
ARG NGINX_VERSION=1.27.5

FROM ${OS_RELEASE}
WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded
ENV CSGHUB_SRV_HOME=${CSGHUB_EMBEDDED}/sv

RUN apt update && \
    apt install -y --no-install-recommends \
      wget git \
      build-essential \
      libpcre2-dev \
      libssl-dev \
      zlib1g-dev \
      libgeoip-dev \
      libgd-dev \
      libxslt-dev \
      pkg-config \
      libedit-dev \
      ca-certificates && \
    apt clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/* && \
    mkdir -p ${CSGHUB_SRV_HOME}/nginx/bin ${CSGHUB_HOME}/etc/nginx/config.d

RUN git clone https://github.com/bellard/quickjs /quickjs && \
    git clone https://github.com/nginx/njs.git /njs

## Install Nginx
ARG NGINX_VERSION
RUN wget --no-check-certificate https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
    tar -zxf nginx-${NGINX_VERSION}.tar.gz && \
    cd /nginx-${NGINX_VERSION} && \
    ./configure \
      --prefix=${CSGHUB_SRV_HOME}/nginx \
      --sbin-path=${CSGHUB_SRV_HOME}/nginx/bin/nginx \
      --conf-path=${CSGHUB_HOME}/etc/nginx/nginx.conf \
      --modules-path=${CSGHUB_HOME}/etc/nginx/modules \
      --pid-path=${CSGHUB_HOME}/etc/nginx/nginx.pid \
      --lock-path=${CSGHUB_HOME}/etc/nginx/nginx.lock \
      --error-log-path=/var/log/csghub/nginx/error.log \
      --http-log-path=/var/log/csghub/nginx/access.log \
      --with-compat \
      --with-http_ssl_module \
      --with-http_geoip_module=dynamic \
      --with-http_realip_module \
      --with-http_image_filter_module=dynamic \
      --with-http_gzip_static_module \
      --with-http_xslt_module=dynamic \
      --with-stream \
      --with-stream_geoip_module=dynamic \
      --add-dynamic-module=/njs/nginx \
      --with-cc-opt="-I/quickjs" \
      --with-ld-opt="-L/quickjs" \
      --with-pcre-jit \
      --with-threads \
      --with-debug && \
    make && make install && \
    rm -rf /nginx* /quickjs /njs

RUN chmod +x -R ${CSGHUB_SRV_HOME}/nginx/bin


