#!/bin/sh -e

# For Upgrade
## $1 ==> upgrade $2 ==> version upgraded
# For Purge
## $1 ==> remove $2 ==> nil

echo "Stopping csghub services..."
systemctl stop csghub-runsvdir.service || true

case "$1" in
  remove)
    systemctl disable csghub-runsvdir.service || true
    ;;

esac

exit 0
