#!/bin/sh -e

# For Upgrade
## $1 ==> upgrade $2 ==> version upgraded
# For Purge
## $1 ==> remove $2 ==> nil

echo "Stopping csghub services..."
if systemctl is-active --quiet csghub-runsvdir.service; then
    echo "Service csghub-runsvdir.service is active, stopping it..."
    systemctl stop csghub-runsvdir.service || true
else
    echo "Service csghub-runsvdir.service is not active."
fi

case "$1" in
  remove)
    systemctl disable csghub-runsvdir.service || true
    ;;

esac

exit 0
