#!/bin/sh -e

# $1 is the action: remove, install, upgrade, failed-upgrade, abort-install etc.

case "$1" in
  upgrade)
    echo "Stopping old version..."
    systemctl stop csghub-runsvdir.service || true
    ;;

esac

exit 0
