ARG REGISTRY=docker.io
ARG OS_RELEASE=ubuntu:22.04
ARG TEMPORAL_VERSION=1.29.7
ARG TEMPORAL_UI_VERSION=2.48.4

FROM ${REGISTRY}/temporalio/auto-setup:${TEMPORAL_VERSION} AS temporal

FROM ${REGISTRY}/temporalio/ui:${TEMPORAL_UI_VERSION} AS temporal_ui

FROM ${REGISTRY}/golang:1.24.11 AS builder
WORKDIR /

ENV GOPROXY=https://goproxy.cn,direct
ARG TEMPORAL_UI_VERSION

RUN if grep -q -i -E 'debian' /etc/os-release; then \
        find /etc/apt -type f \( -name '*.list' -o -name '*.sources' \) -exec sed -i \
          's|https\?://deb.debian.org/debian-security|http://mirrors.aliyun.com/debian-security|g; s|https\?://deb.debian.org/debian|http://mirrors.aliyun.com/debian|g' {} +; \
    fi && \
    apt update && \
    apt install -y --no-install-recommends curl ca-certificates gcc g++ make && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt install -y --no-install-recommends nodejs && \
    corepack enable && corepack prepare pnpm@latest --activate && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/*

RUN git clone --depth 1 --branch v${TEMPORAL_UI_VERSION} https://github.com/temporalio/ui.git && \
    cd /ui && sed -i '32d' server/server/route/auth.go && \
    sed -i '46s/.*/func validateReturnURL(returnURL string, allowedOrigins []string, requestHost string) error { return nil }/' server/server/route/auth.go && \
    sed -i '47,71d' server/server/route/auth.go && \
    pnpm install && git submodule update && \
    pnpm build:local && pnpm build:server && \
    cd server && \
    CGO_ENABLED=0 GOOS=linux go build -o /ui-server ./cmd/server/main.go

FROM ${REGISTRY}/${OS_RELEASE}
WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded
ENV CSGHUB_SRV_HOME=${CSGHUB_EMBEDDED}/sv

RUN mkdir -p \
      ${CSGHUB_HOME}/etc/temporal/ \
      ${CSGHUB_SRV_HOME}/temporal/bin \
      ${CSGHUB_HOME}/etc/temporal_ui \
      ${CSGHUB_SRV_HOME}/temporal_ui/bin

## Install Temporal & temporal_ui
COPY --from=temporal /usr/local/. ${CSGHUB_SRV_HOME}/temporal/
COPY --from=temporal /etc/temporal/config/. ${CSGHUB_HOME}/etc/temporal/config/
COPY --from=temporal /etc/temporal/schema/. ${CSGHUB_HOME}/etc/temporal/schema/.
COPY --from=temporal_ui /home/ui-server/ui-server ${CSGHUB_SRV_HOME}/temporal_ui/bin/
COPY --from=temporal_ui /home/ui-server/config/. ${CSGHUB_HOME}/etc/temporal_ui/config/
COPY --from=builder /ui-server ${CSGHUB_SRV_HOME}/temporal_ui/bin/

RUN find /opt/csghub/etc/temporal -type f -exec sed -i 's|/etc/temporal|/opt/csghub/etc/temporal|g' {} \;