ARG REGISTRY=docker.io
ARG OS_RELEASE=ubuntu:22.04
ARG GOLANG_VERSION=1.26.3

FROM ${REGISTRY}/${OS_RELEASE} AS downloader
WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded
ENV CSGHUB_SRV_HOME=${CSGHUB_EMBEDDED}/sv
ENV GOPROXY=https://goproxy.cn,direct

RUN if grep -q -i -E 'ubuntu|debian' /etc/os-release; then \
        sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g; s|http://security.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g; s|http://ports.ubuntu.com/ubuntu-ports|http://mirrors.aliyun.com/ubuntu-ports|g' /etc/apt/sources.list && \
        apt update && \
        apt install -y --no-install-recommends \
          wget xz-utils \
          apache2-utils \
          openssh-client \
          build-essential \
          ca-certificates && \
        apt clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/*; \
    else \
        if command -v dnf >/dev/null; then \
            dnf install -y \
              wget xz \
              httpd-tools \
              openssh-clients \
              gcc gcc-c++ make \
              ca-certificates && \
            dnf clean all; \
        else \
            yum install -y \
              wget xz \
              httpd-tools \
              openssh-clients \
              gcc gcc-c++ make \
              ca-certificates && \
            yum clean all; \
        fi; \
        rm -rf /var/cache/yum /tmp/* /var/tmp/* /var/log/*; \
    fi && \
    mkdir -p ${CSGHUB_HOME}/bin ${CSGHUB_EMBEDDED}/bin ${CSGHUB_SRV_HOME}/dnsmasq

## Generate ssh key pairs
RUN ssh-keygen -A

## Install kubectl
ARG KUBECTL_VERSION=v1.33.0
ARG TARGETPLATFORM
RUN case ${TARGETPLATFORM} in \
        "linux/amd64") \
            wget --no-check-certificate -O ${CSGHUB_EMBEDDED}/bin/kubectl https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
            ;; \
        "linux/arm64") \
            wget --no-check-certificate -O ${CSGHUB_EMBEDDED}/bin/kubectl https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/arm64/kubectl \
            ;; \
        *) \
            echo "Unsupported platform: ${TARGETPLATFORM}" && \
            exit 1 \
            ;; \
     esac

## Install htpasswd
RUN cp /usr/bin/htpasswd ${CSGHUB_EMBEDDED}/bin/

ARG DNSMASQ_VERSION=2.91
RUN wget --no-check-certificate -O /dnsmasq.tar.xz https://thekelleys.org.uk/dnsmasq/dnsmasq-${DNSMASQ_VERSION}.tar.xz && \
    mkdir /dnsmasq && tar --strip-components=1 -xJf /dnsmasq.tar.xz -C /dnsmasq && \
    cd /dnsmasq && make && make install PREFIX=${CSGHUB_SRV_HOME}/dnsmasq && \
    mv ${CSGHUB_SRV_HOME}/dnsmasq/sbin ${CSGHUB_SRV_HOME}/dnsmasq/bin && \
    mkdir -p ${CSGHUB_HOME}/etc/dnsmasq && cp dnsmasq.conf.example ${CSGHUB_HOME}/etc/dnsmasq/ && \
    rm -rf /dnsmasq*

FROM ${REGISTRY}/golang:${GOLANG_VERSION} AS builder
WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded
ENV CSGHUB_SRV_HOME=${CSGHUB_EMBEDDED}/sv
ENV GOPROXY=https://goproxy.cn,direct

## Install csghub-ctl
COPY /toolbox/csghub-ctl/. /csghub-ctl/
RUN cd /csghub-ctl && \
    mkdir -p ${CSGHUB_HOME}/bin && \
    CGO_ENABLED=0 go build -buildvcs=false -o ${CSGHUB_HOME}/bin/csghub-ctl cmd/csghub-ctl/csghub-ctl.go

FROM ${REGISTRY}/${OS_RELEASE}
WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded
ENV CSGHUB_SRV_HOME=${CSGHUB_EMBEDDED}/sv

COPY --from=downloader /etc/ssh/ssh_host_* /etc/ssh/
COPY --from=downloader ${CSGHUB_HOME}/etc/. ${CSGHUB_HOME}/etc/
COPY --from=downloader ${CSGHUB_HOME}/bin/. ${CSGHUB_HOME}/bin/
COPY --from=downloader ${CSGHUB_EMBEDDED}/bin/. ${CSGHUB_EMBEDDED}/bin/
COPY --from=downloader ${CSGHUB_SRV_HOME}/dnsmasq/. ${CSGHUB_SRV_HOME}/dnsmasq/
COPY --from=builder ${CSGHUB_HOME}/bin/. ${CSGHUB_HOME}/bin/

RUN chmod +x -R /opt/csghub/bin /opt/csghub/embedded/bin /opt/csghub/embedded/sv/*/bin