ARG REGISTRY=docker.io
ARG OS_RELEASE=ubuntu:22.04

FROM ${REGISTRY}/${OS_RELEASE}
WORKDIR /

ENV CSGHUB_HOME=/opt/csghub
ENV CSGHUB_EMBEDDED=${CSGHUB_HOME}/embedded

RUN if grep -q -i -E 'ubuntu|debian' /etc/os-release; then \
        apt update && \
        apt install -y --no-install-recommends \
          wget \
          build-essential && \
        apt clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/*; \
    else \
        if command -v dnf >/dev/null; then \
            dnf install -y \
              wget \
              gcc gcc-c++ make && \
            dnf clean all; \
        else \
            yum install -y \
              wget \
              gcc gcc-c++ make && \
            yum clean all; \
        fi; \
        rm -rf /var/cache/yum /tmp/* /var/tmp/* /var/log/*; \
    fi && \
    mkdir -p ${CSGHUB_EMBEDDED}/bin

## Install Runit Service Daemon
ARG RUNIT_VERSION=2.1.2
RUN wget --no-check-certificate https://smarden.org/runit/runit-${RUNIT_VERSION}.tar.gz && \
    tar -zxf runit-${RUNIT_VERSION}.tar.gz && \
    cd /admin/runit-${RUNIT_VERSION} && package/install && \
    cp command/* ${CSGHUB_EMBEDDED}/bin && \
    rm -rf /admin/runit-${RUNIT_VERSION} /runit-${RUNIT_VERSION}.tar.gz

RUN chmod +x -R ${CSGHUB_EMBEDDED}/bin
