#!/bin/sh
{{- $dataDir := (datasource "config").postgresql.data_dir | default "/var/opt/csghub/postgresql/data" }}
if [ -f "{{ $dataDir }}/postmaster.pid" ]; then
    /opt/csghub/embedded/bin/pg_ctl stop -D "{{ $dataDir }}" -m fast
fi

while pgrep -F "{{ $dataDir }}/postmaster.pid" >/dev/null 2>&1; do
    sleep 1
done

exit 0